name: github-action
env:
  apikey: 3ee88ae5819c48e5e7555553
  apisecret: c36e4ac2d454704b0923a9988b4ba9b3309303275fe838d4c922d2563d3bfc3c966cad03
  testid: '13033948'
  ContinuePipeline: 'false'
  showtaillog: 'false'
  inputstartfile: "abc.txt"

'on': push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v8.1
        id: run-test
        with:
          apikey: '${{env.apikey}}'
          apisecret: '${{env.apisecret}}'
          testid: '${{env.testid}}'
          ContinuePipeline: '${{env.ContinuePipeline}}'
          showtaillog: '${{env.showtaillog}}'
          inputstartfile: '${{env.inputstartfile}}'
